services:
  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: Services/Users/Users.Api/Dockerfile
    ports:
      - "5000:80" 
    depends_on:
      - event-system-dbserver
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=event-system-dbserver;Database=UsersDb;User=sa;Password=P@55w0rd_fgr_2025;Encrypt=false;TrustServerCertificate=true;
    networks:
      - eventnet

  authentication.api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: Services/Authentication/Authentication.Api/Dockerfile
    depends_on:
      - event-system-dbserver
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=event-system-dbserver;Database=AuthDb;User=sa;Password=P@55w0rd_fgr_2025;Encrypt=false;TrustServerCertificate=true;
    networks:
      - eventnet

  tickets.api:
    image: ${DOCKER_REGISTRY-}ticketsapi
    build:
      context: .
      dockerfile: Services/Tickets/Tickets.Api/Dockerfile
    depends_on:
      - event-system-dbserver
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=event-system-dbserver;Database=TicketsDb;User=sa;Password=P@55w0rd_fgr_2025;Encrypt=false;TrustServerCertificate=true;
    networks:
      - eventnet
  
  orchestration.api:
    image: ${DOCKER_REGISTRY-}orchestrationapi
    build:
      context: .
      dockerfile: Services/Orchestration/Orchestration.Api/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - eventnet
      
  payments.api:
    image: ${DOCKER_REGISTRY-}paymentsapi
    build:
      context: .
      dockerfile: Services/Payments/Payments.Api/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - eventnet


  event-system-dbserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "P@55w0rd_fgr_2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - eventnet
       
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - eventnet  

networks:
  eventnet:
    driver: bridge




